"""
KisanMind Report Compilation Agent
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Takes outputs from all 4 specialist agents and compiles
them into a structured bilingual (Hindi + English)
advisory report in clean markdown format.
Also triggers PDF generation.
"""

import json
import time

from models.state import KisanMindState
from utils.llm_provider import get_llm


async def run_report_agent(state: KisanMindState) -> KisanMindState:
    """
    LangGraph node: Compile all agent results into a
    bilingual advisory report.
    """
    start = time.time()

    try:
        disease = state.get("disease_result")
        market = state.get("market_result")
        scheme = state.get("scheme_result")
        weather = state.get("weather_result")
        errors = state.get("errors") or {}
        crop_type = state.get("crop_type", "crop")
        location = state.get("location", "India")
        query = state.get("query", "")

        # Build context for the LLM
        agent_data = {
            "farmer_query": query,
            "crop_type": crop_type,
            "location": location,
            "disease_analysis": disease if disease else "No image provided or analysis unavailable",
            "market_intelligence": market if market else "Market data unavailable",
            "government_schemes": scheme if scheme else "Scheme data unavailable",
            "weather_advisory": weather if weather else "Weather data unavailable",
            "agent_errors": errors if errors else "None",
        }

        llm = get_llm()

        prompt = f"""You are KisanMind, an AI agricultural advisor for Indian farmers.
Compile the following agent outputs into a comprehensive, bilingual advisory report.

Agent Data:
{json.dumps(agent_data, indent=2, default=str)}

Create a CLEAN MARKDOWN report with this exact structure:

# 🌾 KisanMind Advisory Report / किसानमाइंड सलाहकार रिपोर्ट

## Farmer Query / किसान का प्रश्न
[Original query in both languages]

## 🔬 Crop Health Analysis / फसल स्वास्थ्य विश्लेषण
[Disease findings, treatment, dosage — or "No image provided"]

## 📊 Market Intelligence / बाजार बुद्धिमत्ता
[Current prices, trend, best mandi, buy/sell recommendation, 7-day prediction]

## 🏛️ Government Schemes / सरकारी योजनाएं
[Eligible schemes with application steps]

## 🌤️ Weather Advisory / मौसम सलाह
[Today's weather, 3-day forecast, spray advisory, irrigation advice]

## 📋 Summary & Action Items / सारांश और कार्य योजना
[3-5 bullet points of immediate actions the farmer should take]

---
*Report generated by KisanMind AI Advisory System*

Rules:
- Every section header must be bilingual (English / Hindi)
- Key recommendations must be in BOTH Hindi and English
- Use farmer-friendly language, avoid jargon
- If an agent failed, mention data is partially available
- Include specific numbers: prices in ₹, dosages in ml/acre, temperatures in °C
- Format as clean markdown with proper headers, bold text, and bullet points
"""

        response = await llm.ainvoke(prompt)
        report_md = response.content.strip()

        # Generate PDF (best-effort, don't fail if PDF fails)
        pdf_path = None
        try:
            from utils.pdf_generator import generate_pdf

            pdf_path = generate_pdf(report_md, state.get("session_id", "unknown"))
        except Exception:
            pass  # PDF generation is non-critical

        elapsed = time.time() - start
        agent_times = dict(state.get("agent_times") or {})
        agent_times["report_agent"] = round(elapsed, 3)

        return {
            "final_report": report_md,
            "agent_times": agent_times,
        }

    except Exception as e:
        elapsed = time.time() - start
        agent_times = dict(state.get("agent_times") or {})
        agent_times["report_agent"] = round(elapsed, 3)
        errors = dict(state.get("errors") or {})
        errors["report_agent"] = str(e)

        # Fallback: build a simple report without LLM
        fallback = _build_fallback_report(state)

        return {
            "final_report": fallback,
            "agent_times": agent_times,
            "errors": errors,
        }


def _build_fallback_report(state: KisanMindState) -> str:
    """Create a basic report if the LLM fails."""
    sections = ["# 🌾 KisanMind Advisory Report\n"]
    sections.append(f"**Query:** {state.get('query', 'N/A')}\n")
    sections.append(f"**Crop:** {state.get('crop_type', 'N/A')} | **Location:** {state.get('location', 'N/A')}\n")

    if state.get("disease_result"):
        sections.append("## 🔬 Disease Analysis\n")
        sections.append(f"```json\n{json.dumps(state['disease_result'], indent=2)}\n```\n")

    if state.get("market_result"):
        sections.append("## 📊 Market Data\n")
        sections.append(f"```json\n{json.dumps(state['market_result'], indent=2)}\n```\n")

    if state.get("scheme_result"):
        sections.append("## 🏛️ Schemes\n")
        sections.append(f"```json\n{json.dumps(state['scheme_result'], indent=2)}\n```\n")

    if state.get("weather_result"):
        sections.append("## 🌤️ Weather\n")
        sections.append(f"```json\n{json.dumps(state['weather_result'], indent=2)}\n```\n")

    return "\n".join(sections)
